// This file is automatically generated. Do not edit it directly.
// Ajuste transitório do reboot: a conexão aponta para o banco novo
// (tysvpeprhokdijquprkd), que ainda não tem as tabelas do portal legado.
// Enquanto as telas são migradas (Fases 4 a 6), o cliente é exportado sem
// tipagem estrita para que o portal antigo continue compilando.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://tysvpeprhokdijquprkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5c3ZwZXByaG9rZGlqcXVwcmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzNTE0MTEsImV4cCI6MjEwMzkyNzQxMX0.GrdVZ7Xtw3dk4zy9Y29sGGAdOcx4Lq9-I--osYirHIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Cliente tipado pelo schema novo — usar nas telas do reboot.
export const supabaseTipado = client;

// Cliente usado pelo código legado (sem tipagem estrita).
export const supabase = client as unknown as SupabaseClient<any, any, any>;
